title: DOFH
description: Tales from the intersection of bureaucracy, technology and unintended consequences.

theme: jekyll-theme-hacker

baseurl: "/dofh"
url: "https://thebiggeek.github.io"

header_pages:
  - episodes.md
  - lore.md
  - about.md
